language: ruby
sudo_enabled: true
services:
  - docker
before_install:
  - wget https://github.com/cloud66/habitus/releases/download/0.4.9/habitus_darwin_amd64 -o habitus
  - chmod +x habitus
  - sudo cp habitus /bin/habitus
script:
  - sudo ./habitus
