language: ruby
sudo_enabled: true
services:
  - docker
before_install:
  - sudo wget https://github.com/cloud66/habitus/releases/download/0.4.9/habitus_linux_amd64 -o habitus
  - sudo chmod +x habitus
  - sudo cp habitus /bin/habitus
script:
  - sudo ./habitus --no-cache
